

- name: Restart k3s
  hosts: k3s_cluster
  tasks:
    - name: Restart k3s systemd
      ansible.builtin.systemd:
        name: k3s
        state: restarted
      retries: 3
      delay: 3
      register: k3s_systemd_restart_k3s
      failed_when:
        - k3s_systemd_restart_k3s is not success
      become: true






