#
# Description: This playbook retrieves the k3s and kubectl versions using kubectl on the first server
#               of the cluster.
#
# More details: https://docs.k3s.io/cli/token#server
#
---
- name: Retrieve versions from server
  hosts: k3s_cluster[0]
  gather_facts: true
  become: true
  tasks:
    - name: Echo versions
      command: /usr/local/bin/kubectl version
      register: results

    - ansible.builtin.debug:
        msg: '{{ results.stdout_lines }}'