#
# Description: This playbook
#
---
- name: Test playbook
  hosts: k3s_cluster
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
